version: '2'

services:
  redis:
    image: redis:latest
  app:
    build: .
    container_name: Test_Project_Emaww
    ports:
      - "80:3000"
    environment:
      - REDIS_URI=redis://redis:6379
    volumes:
      - .:/var/app/project
    command: sh -c 'npm i && npm start'
